package cn.infrastructure.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import cn.infrastructure.db.dao.CrashLogDao;
import cn.infrastructure.db.entity.CrashLog;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig crashLogDaoConfig;

    private final CrashLogDao crashLogDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        crashLogDaoConfig = daoConfigMap.get(CrashLogDao.class).clone();
        crashLogDaoConfig.initIdentityScope(type);

        crashLogDao = new CrashLogDao(crashLogDaoConfig, this);

        registerDao(CrashLog.class, crashLogDao);
    }
    
    public void clear() {
        crashLogDaoConfig.clearIdentityScope();
    }

    public CrashLogDao getCrashLogDao() {
        return crashLogDao;
    }

}
